---
- hosts: regn
  become: yes
  vars:
    nginx_app_domain_name: "www.kartan.no"
    nginx_app_webroot: /var/www/{{nginx_app_domain_name}}
    letsencrypt_email: kjartanbjorset@gmail.com
    local_project_dir: "{{ playbook_dir.split('/')[0:-1]|join('/') }}"
    
  # roles:
    # - ansible-role-nginx-certbot-app
    # - role: deploy-app

  tasks:
    - name: ensure github.com is a known host
      lineinfile:
        dest: /home/git/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - git: repo=ssh://git@github.com/kjartab/site dest=/home/git/site
      become_user: git

    - file: src={{local_project_dir}}/hooks/post-receive dest=/home/git/site/.git/hooks/post-receive

    
  