---
- hosts: regn
  become: yes
  vars:
    nginx_app_domain_name: "www.kartan.no"
    nginx_app_webroot: /var/www/{{nginx_app_domain_name}}
    letsencrypt_email: kjartanbjorset@gmail.com
    local_project_dir: "{{ playbook_dir.split('/')[0:-1]|join('/') }}"
    
  # roles:
    # - ansible-role-nginx-certbot-app
    # - role: deploy-app

  tasks:

    - group: name=web
    
    - user: 
        name: git
        group: web

    - name: ensure github.com is a known host
      lineinfile:
        dest: /home/git/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    # - git: repo=ssh://git@github.com/kjartab/site dest=/home/git/site bare=yes
    #   become_user: git
    - file: path=/home/git/site.git state=directory
      become_user: git

    - shell: cd /home/git/site.git && git init --bare
      become_user: git
      
    - copy: src={{local_project_dir}}/hooks/post-receive dest=/home/git/site.git/hooks/post-receive owner=git

    - file: path=/home/git/site.git/hooks/post-receive mode=a+x

    - file: 
        path: /var/www
        group: web
        mode: 0775
        recurse: yes